language: node_js
node_js:
  "10"
cache:
  directories:
    - "node_modules"
script:
  - npm run build
  - mkdir dist
  - cp index.html icon.png dist/
  - cp -r assets dist/
  - cp -r build dist/
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master